name: Pull request

on:
  pull_request:
    branches: ["main", "develop", "develop/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yaml
